### ISSUE TITLE
In `coc.nvim` latest release, startup `coc-deno` failed

### ISSUE THREAD

**Issue by gamoutatsumi** [fannheyward/coc-deno#109]
I updated coc.nvim today, encountered this error.

`[coc.nvim] Error on activate extension coc-deno: api.configurePlugin is not a function`

That seems caused by [this](https://github.com/neoclide/coc.nvim/commit/c02be2e34489b39aa2c3de25c3e08993f84526bd) change.

https://github.com/fannheyward/coc-deno/blob/dcaa653620fb83c6f588fbdfe7fc1cac5ffa779b/client/src/extension.ts#L72-L78

`tsserver` is no longer provide `exports`.

**Comment by gamoutatsumi** [comment]
As workaround, replacing `tsserver.exports` to `tsserver.result` looks like well.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by gamoutatsumi** [comment]
It's working.
Thanks.
