### ISSUE TITLE
Deno Import missing prefix for deno import_map.json

### ISSUE THREAD

**Issue by Lite5h4dow** [fannheyward/coc-deno#118]
hi, im using the import.json to manage my imports, however coc-deno dosent seem to detect them.
this isnt a problem in vscode, so i think this is a problem with coc-deno but i may be wrong.
a file call it api1.ts
![Screenshot 2021-09-03 at 12 05 01](https://user-images.githubusercontent.com/18059545/131995756-e32bd9d1-e409-4ed1-b9af-ef23855025fa.png)
import_map.json
![Screenshot 2021-09-03 at 12 09 21](https://user-images.githubusercontent.com/18059545/131996253-e9a0489b-83f3-4dcb-b48f-d568868fd683.png)

**Comment by Lite5h4dow** [comment]
hi there, i haven't heard anything on here in a while. do you need any info or anything?

**Comment by fannheyward** [comment]
Sorry for the delay, I'll check this  in the weekend.

**Comment by Lite5h4dow** [comment]
did you get the chance to look at it?

**Comment by fannheyward** [comment]
I'm working on this, but with a weird behavior.

Sample code, main.ts:

```ts
import { Application } from "https://deno.land/x/oak@v9.0.0/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

console.log("oak serve on 8000");
await app.listen({ port: 8000 });
```

This code can be built and run as expected.

Now I set this import_map.json:

```json
{
  "imports": {
    "oak": "https://deno.land/x/oak@v9.0.0/mod.ts"
  }
}
```

And change the import to `import { Application } from "oak";`, now the VSCode + Deno failed, and `deno run --allow-net main.ts` failed too.

<img width="620" alt="截屏2021-09-13 上午9 43 32" src="https://user-images.githubusercontent.com/345274/133011976-462871df-ac8e-4778-896a-08e303743525.png">

```
❯ deno run --allow-net main.ts
error: Relative import path "oak" not prefixed with / or ./ or ../ from "file:///Users/fannheyward/src/hello-deno/main.ts"
```

BUT, coc.nvim + coc-deno works:

<img width="772" alt="截屏2021-09-13 上午9 44 10" src="https://user-images.githubusercontent.com/345274/133012002-570adfbf-f0c9-4b14-9d96-624d5d9d088a.png">

**Comment by Lite5h4dow** [comment]
this is very odd. in vscode it works fine for me:
![image](https://user-images.githubusercontent.com/18059545/133063321-f4d05234-fe0d-4a88-8941-93943d11f87a.png)

and I don't even need to specify my `import_map.json` although that might be more to do with the fact I'm launching with aleph cli, not plain deno.

however in Coc-Deno i get the following: 
![image](https://user-images.githubusercontent.com/18059545/133063793-0426cea2-3818-4f2f-98ab-5c021e473ac1.png)

(this is a fresh install of coc-deno)

**Comment by Lite5h4dow** [comment]
![image](https://user-images.githubusercontent.com/18059545/133064327-a360e889-1285-48ba-8dd6-972ab77af243.png)
im using latest iirc

![image](https://user-images.githubusercontent.com/18059545/133064403-972462c7-e10e-40de-85fd-983e811d5db1.png)
here is the error and the version in the same image

**Comment by fannheyward** [comment]
What's the content of `.vim/coc-settings.json` in your project?

**Comment by Lite5h4dow** [comment]
that file dosent exist. is it supposed to?

**Comment by fannheyward** [comment]
Can you test with my sample code here? https://github.com/fannheyward/coc-deno/issues/118#issuecomment-917770334

**Comment by Lite5h4dow** [comment]
![image](https://user-images.githubusercontent.com/18059545/133068401-b0de1c78-37d3-47ef-91fb-f4ad8a851bb1.png)

**Comment by Lite5h4dow** [comment]
with your example code completed:
![image](https://user-images.githubusercontent.com/18059545/133068957-9f2dd3c1-40b7-463a-bae5-e4c79f8c3ae7.png)

**Comment by Lite5h4dow** [comment]
i figured out what was missing
![image](https://user-images.githubusercontent.com/18059545/133071633-311374a6-1511-47dd-9e75-254873ee614b.png)

**Comment by deerox999** [comment]
> i figured out what was missing ![image](https://user-images.githubusercontent.com/18059545/133071633-311374a6-1511-47dd-9e75-254873ee614b.png)

that was correct, thanks
