### ISSUE TITLE
Question regarding tsserver

### ISSUE THREAD

**Issue by owohl** [fannheyward/coc-deno#132]
Hello. 
I'm trying to start a new deno mini-project and I've installed both coc-deno and coc-tsserver thinking I can use them together but upon initializing the deno project as shown in the readme it seems tsserver is disabled. Why is that ? Doesn't a deno project need a typescript lsp ?
Just to be more specific it's just a small typescript web scraper that will need cheerio and urlcat and I plan to use deno to launch it.

**Comment by fannheyward** [comment]
You don't need tsserver for Deno project, `deno lsp` will take care for your Deno codes.

**Comment by owohl** [comment]
> You don't need tsserver for Deno project, `deno lsp` will take care for your Deno codes.

Yes but what about the typescript in the Deno project ?

**Comment by fannheyward** [comment]
`deno lsp` works for TypeScript too for Deno project.
