### ISSUE TITLE
`:CocCommand deno.initializeWorkspace` doesn't let me select items

### ISSUE THREAD

**Issue by sae3023** [fannheyward/coc-deno#137]
I'm sorry that I have to ask such a stupid questions, but I'm feeling completely stuck, I'm trying to pick up vim as my main editor.

I'm trying to run `:CocCommand deno.initializeWorkspace`, the dialog picker shows up, but I cannot select an item in the picker, as `<cr>` just tosses me out of the dialog.

Here's a screenshot.
![image](https://user-images.githubusercontent.com/68739556/145897867-aaddd647-36ec-4f3e-91bc-e9ef5b319780.png)

**Comment by yaegassy** [comment]
You can use the "SPACE" key to check an item.

**Comment by sae3023** [comment]
I feel so dumb.

Thank you.
