### ISSUE TITLE
CocRestart not needed for disable tsserver

### ISSUE THREAD

**Issue by chemzqm** [fannheyward/coc-deno#147]
coc-tsserver 1.9.10 could watch for that configuration.
https://github.com/fannheyward/coc-deno/blob/e7195b87c29d79b7f000b00797631260ddd53c5a/src/commands.ts#L175

**Comment by fannheyward** [comment]
Testing with coc-tsserver 1.9.11, after set `tsserver.enable` to false, the coc-tsserver is still activated.

**Comment by chemzqm** [comment]
No need to reload the extensions, I've fixed coc-tsserver to clear diagnostics on dispose.
