### ISSUE TITLE
String literal can break highlighting of the next lines

### ISSUE THREAD

**Issue by sigmaSd** [fannheyward/coc-deno#153]
```ts
 `a:`;
let a = 4// the color is wrong on this line
```
![Screenshot from 2022-03-15 20-22-15](https://user-images.githubusercontent.com/22427111/158455364-e642a28a-624c-4b59-9ffc-33a1f86a7e25.png)

**Comment by sigmaSd** [comment]
```ts
 `a:`;
let a = 4// the color is wrong on this line
```

**Comment by fannheyward** [comment]
Can't reproduce, should be caused by other plugins, try minimal vimrc.

**Comment by sigmaSd** [comment]
turn out that's not the enough to reproduces the issue, I minimized it to the following code
```ts
((
  { a }: { a: any },
) => {
  `a:`; // all lines after this are highlighted incorrectly
});
```

**Comment by fannheyward** [comment]
Still can't reproduce:

<img width="583" alt="截屏2022-03-19 12 02 14" src="https://user-images.githubusercontent.com/345274/159105928-da5edacc-e8b5-4ced-915e-955634cc4e58.png">

**Comment by sigmaSd** [comment]
OK thanks for trying it out, I'll try to see If I can add more info later today other wise I'll close this issue.

**Comment by sigmaSd** [comment]
I'm having the same issue with coc-tsserver, I'm not sure how to debug highlighting but here is some meta info in case that helps 
```
## versions

vim version: NVIM v0.6.1
node version: v17.7.1
coc.nvim version: 0.0.80-0b4b683e 2022-03-18 05:46:15 +0800
coc.nvim directory: /home/user/local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux
```
