### ISSUE TITLE
tsserver still work

### ISSUE THREAD

**Issue by bigshans** [fannheyward/coc-deno#158]
This is my configuration in project root.

``` json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "tsserver.enable": false
}
```

Here is my code:

``` typescript
import { serve } from "https://deno.land/std/http/server.ts";

serve(() => new Response('Hello World!'));
```

The code works well. But tsserver still throws an import error. No problem on vscode.

Tsserver should be disabled here, but it didn't take effect.

**Comment by fannheyward** [comment]
What's your coc-tsserver version? You can get it from `:CocList extensions`.

**Comment by bigshans** [comment]
> What's your coc-tsserver version? You can get it from `:CocList extensions`.

coc-tsserver v1.10.0
coc-deno v3.9.2

**Comment by fannheyward** [comment]
Tested with same versions, still can't reproduce.
