### ISSUE TITLE
[coc.nvim]: Unable to locate workspace folder configuration for {project path}

### ISSUE THREAD

**Issue by js-writer** [fannheyward/coc-deno#180]
When I'm doing `:CocCommand deno.initializeWorkspace` and I hit enter than I get this error:
`[coc.nvim]: Unable to locate workspace folder configuration for`
I'm on Windows 10;
I have this settings in my init.vim

`let g:coc_config_home = 'C:\Users\{myuser}\AppData\Local\nvim'`
`let g:coc_data_home = 'C:\Users\{myuser}\AppData\Local\coc'`

**Comment by fannheyward** [comment]
Please post `:CocOpenLog` full error logs.

**Comment by js-writer** [comment]
Here it is:
`2022-09-16T11:27:09.586 INFO (pid:4244) [plugin] - coc.nvim initialized with node: v16.14.2 after 196ms^M
  1 2022-09-16T11:27:13.932 INFO (pid:4244) [attach] - receive notification: runCommand [ 'deno.initializeWorkspace' ]^M  2 2022-09-16T11:27:15.813 ERROR (pid:4244) [configurations] - Unable to locate workspace folder configuration C:\test     Error
  3     at Object.update (C:\Users\{user}\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:158:13353)
  4     at doInitialize (C:\Users\{user}\AppData\Local\coc\extensions\node_modules\coc-deno\lib\index.js:2405:10)
  5     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  6     at async C:\Users\{user}\AppData\Local\coc\extensions\node_modules\coc-deno\lib\index.js:2620:7
  7     at async Dne.fireCommand (C:\Users\{user}\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:268:28981)
  8     at async VC.runCommand (C:\Users\{user}\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:272:16790)
  9     at async Rx.cocAction (C:\Users\{user}\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:292:20110)
 10     at async $H.<anonymous> (C:\Users\{user}\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:292:21687)^M 11`

**Comment by fannheyward** [comment]
This has been fixed on coc.nvim https://github.com/neoclide/coc.nvim/issues/4207
