### ISSUE TITLE
Code Lens Run Test should use a pattern to filter exact tests.

### ISSUE THREAD

**Issue by martin-braun** [fannheyward/coc-deno#185]
Running the first test using the keybinding for `<Plug>(coc-codelens-action)` will cause both tests to be executed: 

```ts
Deno.test("[io] myTest", function () {
});

Deno.test("[io] myTest2", function () {
	throw new AssertionError("This test must not run!");
});
```

This is because it runs: 

```sh
deno test --allow-all --unstable --filter "[io] myTest" my_test.ts
```

But it actually should run the command with a regex pattern filter: 

```sh
deno test --allow-all --unstable --filter "/^\[io\] myTest$/" my_test.ts
```

Only then it matches only the current test.

**Comment by fannheyward** [comment]
Reproduced

**Comment by martin-braun** [comment]
@fannheyward I have all my `coc` extensions managed in `g:coc_global_extensions`. I assume updating should work through `PackerSync`, it's not? The change is not available or working for me.

Am I missing something?

**Comment by fannheyward** [comment]
@martin-braun no, extensions are updated by `CocUpdate`.

**Comment by martin-braun** [comment]
@fannheyward Thanks, new to CoC, worked like charm, now I see your changes.
