### ISSUE TITLE
Why is there a need to run CocCommand deno.initializeWorkspace ?

### ISSUE THREAD

**Issue by myarcana** [fannheyward/coc-deno#194]
Why can't it just work like any other language server? Without a manual initialisation necessary in every file?

I don't think it should need to make a `.vim/` just to stop "An import path cannot end with a '.ts' extension" etc. linter errors from appearing. deno can run files that are placed anywhere, there is no requirement for a project or workspace filesystem container. Therefore I think that a deno language server shouldn't force you to have one either.

**Comment by patreeceeo** [comment]
FWIW, it seems I can delete the `.vim/` directory and the plugin works fine.

**Comment by fannheyward** [comment]
1. the configuration `deno.enable` is disabled by default, same as vscode_deno as it's not recommended to be enabled global. The extension will check `deno.enable` to work.
2. the `deno.initializeWorkspace` command will enable `deno.enable`, and disable `coc-tsserver` if installed.

If you're not use coc-tsserver, you can enable `deno.enable` globally in your `:CocConfig`, the command is not needed.
