### ISSUE TITLE
deno no-cache-npm when using import maps for npm modules

### ISSUE THREAD

**Issue by alextricity25** [fannheyward/coc-deno#215]
In my deno.json, I have the following import maps:
```
{
  "imports": {
    "google-cloud/storage": "npm:/@google-cloud/storage"
  }
}
```

In my mod.ts file:
```
import { Storage } from 'google-cloud/storage';

const storage = new Storage();
```
coc-deno is giving me the following error (even after running `CocCommand deno.cache`:

<img width="881" alt="image" src="https://github.com/fannheyward/coc-deno/assets/4964964/755e2ddd-2139-4ac0-ab75-7538cd13b233">

However, when I use the `npm:` specifier, coc-deno seems to know what to do:
<img width="932" alt="image" src="https://github.com/fannheyward/coc-deno/assets/4964964/aabcd5ca-bfbd-431f-8224-0760bcba9729">

**Comment by fannheyward** [comment]
Language server's issue.
