### ISSUE TITLE
How to enable it?

### ISSUE THREAD

**Issue by patrickReiis** [fannheyward/coc-deno#242]
I installed the extension using `:CocInstall coc-deno` then I ran `:CocCommand deno.initializeWorkspace` and a screen pops up, I press enter to accept "Enable Deno linting".
I enable the extension in the `:CocList extensions` part.

Nothing happens. When I run the CocCommand `deno.status` a screen pops up with a lot of settings, I see the "enable: false" field, I set it to true and then try to save the file, but nvim doesn't allow, it says: ` Cannot write, 'buftype' option is set`

I suppose I should enable it in the `coc-settings.json`, the problem is that I don't know how to set it in the coc-settings.json to enable coc-deno.

My coc-settings.json is an empty file. I know this is a simple question but could you provide a sample `coc-settings.json` file enabling the coc-deno? I would appreciate it, thanks.

**Comment by fannheyward** [comment]
After you run `deno.initializeWorkspace`٫ check your `CocLocalConfig`, the `deno.enable` should be true.

**Comment by patrickReiis** [comment]
There's only a `{"tsserver.enable": false}` JSON, I'll delete it in put `{"deno.enable": true}`.

But this part I could fix, I mean, now there is auto completion and stuff, the only problem is that there is no hinting on the variable type, and I can't jump to the definition.

I already enabled the required fields, such as `"deno.inlayHints.variableTypes.enabled": true,` and `"deno.inlayHints.propertyDeclarationTypes.enabled": true,` but it doesn't work.

**Comment by fannheyward** [comment]
`:CocInfo` please.

**Comment by yaegassy** [comment]
@patrickReiis 

Please try changing the settings for deno's inlayHints to those for the typescript and javascript prefixes. I believe that inlayHints with the deno prefix are deprecated.

**e.g.**:

```jsonc
{
  // ...snip
  "typescript.inlayHints.parameterNames.enabled": "all",
  "typescript.inlayHints.enumMemberValues.enabled": true,
  "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
  "typescript.inlayHints.propertyDeclarationTypes.enabled": true,
  "typescript.inlayHints.parameterTypes.enabled": true,
  "typescript.inlayHints.variableTypes.enabled": true,
  "typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true,
  "javascript.inlayHints.parameterNames.enabled": "all",
  "javascript.inlayHints.variableTypes.enabled": true,
  "javascript.inlayHints.parameterTypes.enabled": true,
  "javascript.inlayHints.enumMemberValues.enabled": true,
  "javascript.inlayHints.functionLikeReturnTypes.enabled": true,
  "javascript.inlayHints.propertyDeclarationTypes.enabled": true,
  "javascript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true,
  // ...snip
}
```

**Comment by fannheyward** [comment]
>  the deno prefix are deprecated

@yaegassy any source? I've checked vscode_deno, same configuration with deno prefix.

**Comment by patrickReiis** [comment]
@yaegassy 
![image](https://github.com/fannheyward/coc-deno/assets/76563803/71935622-592d-40aa-aa6b-d8fd46b8fd66)

**Comment by yaegassy** [comment]
@fannheyward I believe there was a change from the deno prefix to typescript and javascript around this commit.

- <https://github.com/denoland/vscode_deno/pull/981>
- <https://github.com/denoland/deno/pull/20593>

Ah..., it seems that the `deno.inlayHints.*` settings are still respected, albeit deprecated.

**Comment by patrickReiis** [comment]
`
 1 ## versions                                                                                                                                                                               
  2 
  3 vim version: NVIM v0.7.2
  4 node version: v16.15.0
  5 coc.nvim version: 0.0.82-ede39ea9 2024-03-28 17:57:50 +0800
  6 coc.nvim directory: /home/winlectro/.vim/plugged/coc.nvim
  7 term: xterm-256color
  8 platform: linux
  9 
 10 ## Log of coc.nvim
 11 
 12 2024-03-29T21:01:22.583 INFO (pid:12013) [configurations] - Add folder configuration from cwd: /home/winlectro/Documents/Dev/mine-ditto/ditto/.vim/coc-settings.json
 13 2024-03-29T21:01:22.631 INFO (pid:12013) [plugin] - coc.nvim initialized with node: v16.15.0 after 84
 14 2024-03-29T21:01:22.632 INFO (pid:12013) [services] - LanguageClient deno state change: stopped => starting
 15 2024-03-29T21:01:22.638 INFO (pid:12013) [language-client-index] - Language server "deno" started with 12054
 16 2024-03-29T21:01:22.706 INFO (pid:12013) [services] - LanguageClient deno state change: starting => running
 17 2024-03-29T21:01:22.709 INFO (pid:12013) [services] - service deno started                                             
`

@fannheyward

**Comment by fannheyward** [comment]
@yaegassy thank you for the links, will upgrade our configurations later.

**Comment by patrickReiis** [comment]
The coc-deno works, the only thing that doesn't work is the variable hint and also I can't see jump to the definition of functions.

**Comment by yaegassy** [comment]
@patrickReiis It seems that Neovim itself is quite an old version. It might be a good idea to try upgrading Neovim.

**Comment by fannheyward** [comment]
> vim version: NVIM v0.7.2 4

@patrickReiis you're using an old version nvim with latest coc.nvim. 

coc.nvim has added inline inlayHint support for nvim, similar to Vim 9, https://github.com/neoclide/coc.nvim/pull/4648, this requires nvim 0.10+.

Yes, this is a breaking change for stable users, two solutions:

1. using nvim 0.10.0 nightly
2. or downgrade your coc.nvim to https://github.com/neoclide/coc.nvim/commit/3dc6153a85ed0f185abec1deb972a66af3fbbfb4

**Comment by patrickReiis** [comment]
Switched to Asynchronous Lint Engine (ALE), I appreciate you guys for helping me.
