### ISSUE TITLE
deno.cache command seems deleted? (accidentally?)

### ISSUE THREAD

**Issue by LumaKernel** [fannheyward/coc-deno#248]
`CocCommand deno.` completion does not show `deno.cache` and if I run `CocCommand deno.cache` I'll get the following error. (while it succeeds `CocCommand deno.status`)

```
[coc.nvim]: Error on notification "runCommand": invalid length 0, expected tuple struct Arguments with 3 element
```

deno.cache is described in README as well, so it sounds better to remove that description if it's an intentional change.

Tested on:
- NVIM v0.9.5
- coc-deno 3.14.0 (latest)
- deno 1.43.3 (release, x86_64-unknown-linux-gnu)

**Comment by LumaKernel** [comment]
oops, I can't find the last version there're deno.cache command...
Possibly the problem of deno version...?

**Comment by fannheyward** [comment]
Added `deno.cacheActiveDocument` command as `deno.cache` is now an internal command.
