### ISSUE TITLE
After installing coc-deno JavaScript files give TypeScript errors

### ISSUE THREAD

**Issue by alextes** [fannheyward/coc-deno#25]
file.js
```
const fn = (arg) => undefined;
```
I get the error:
```
Error [tsserver 7006] Parameter 'arg' implicitly has an 'any' type.
```

When running:

yarn tsc --allowJs --noEmit file.js
No implicit any error, and why would there be? This is a JS file.

Any idea how I could get back to tsserver checking js files but without giving me errors that only apply to ts files?

**Comment by fannheyward** [comment]
You should disable this extension for non-deno project. Same issue #7.

**Comment by alextes** [comment]
Well yea but doing that every time I open vim for a JS project gets old quick 😅 . I appreciate the workaround though. Thanks for linking the other issue, will subscribe to that one!

**Comment by pietvanzoen** [comment]
@alextes did you find anything useful regarding this issue?

It seems that even if I have `deno.enable` set to `false` tsserver is still treating js files as ts.

**Comment by alextes** [comment]
@pietvanzoen nope. I'm not working with deno much so for me it's workable to uninstall / reinstall coc-deno when I need it.

Check #7 for progress on this.

**Comment by pietvanzoen** [comment]
gotcha... thanks!

**Comment by pheuberger** [comment]
I don't even have deno installed, but I still get these warnings in a Javascript project. Any ideas?

**Comment by alextes** [comment]
@pheuberger did you try uninstalling coc-deno?
```
:CocUninstall coc-deno
```

If you did, and you're _still_ getting them, it's not this plugin.
