### ISSUE TITLE
deno.types not found

### ISSUE THREAD

**Issue by zohaad** [fannheyward/coc-deno#26]
When running `:CocCommand deno.types` in a hello.ts file I get `[coc.nvim] Command: deno.types not found`.

`:healthcheck` for `health#coc#check` is all green.

`deno.types` and `deno.cache` both show up when `:CocList commands`, however when doing `:CocCommand<CR>`, they don't show up.

there is no `:CocConfig` file

**Comment by fannheyward** [comment]
Does `hello.ts` exists?

**Comment by zohaad** [comment]
yes, `deno run hello.ts` works

**Comment by zohaad** [comment]
Doing `:CocInstall coc-tsserver` and restarting nvim fixes the issue.
