### ISSUE TITLE
Disable coc-deno for Node.js projects

### ISSUE THREAD

**Issue by brillout** [fannheyward/coc-deno#54]
I work on both Deno and Node.js projects. Is there a way for `coc-deno` to automatically disable itself when using nvim for a Node.js project?

Thanks for your coc plugin :)

**Comment by fannheyward** [comment]
Try v3.0.0.

**Comment by brillout** [comment]
Neat, thanks!

**Comment by brandonpittman** [comment]
I still have deno errors showing up in every `.ts` file whether they're Deno projects or not.
