### ISSUE TITLE
Switch to denoland/vscode_deno

### ISSUE THREAD

**Issue by carlosala** [fannheyward/coc-deno#63]
Hi!
There are some bugs related to using .js files with coc-deno installed.
This extension uses justjavac/typescript-deno-plugin, that is deprecated now. Would be possible to switch to denoland/vscode_deno? This plugin is actively mantained by denoland community, and fixes some of the errors mencioned in the other issues (for instance, #7).
Thanks for reading that!

**Comment by fannheyward** [comment]
Yes, coc-deno will support `deno lsp`, #55.
