### ISSUE TITLE
Running deno fmt for Deno projects on save?

### ISSUE THREAD

**Issue by wavded** [fannheyward/coc-deno#73]
Currently, `coc-prettier` is formatting Deno projects rather than `deno fmt` which ends up with conflicting styles.  Is there anyway to override this for Deno projects to use `deno fmt` instead?

**Comment by yaegassy** [comment]
How about setting `prettier.disableLanguages` at the project level by running the `:CocLocalConfig` command?

**(Example) .vim/coc-settings.json**

```jsonc
{
  // ...snip
  "prettier.disableLanguages": [
    "typescript",
    "javascript"
  ]
  // ...snip
}
```

**Comment by wavded** [comment]
Nice, perhaps this could be an option when initializing a project @fannheyward ?

**Comment by igorbrasileiro** [comment]
Does this option to formatOnSaveFileType: ["typescript", "javascript"] is enabled by default? If not, how can I enable it for "jsx, tsx, js, tsx" files?

**Comment by fannheyward** [comment]
@igorbrasileiro you can add `"typescript", "typescriptreact", "javascript", "javascriptreact"` to your `coc.preferences.formatOnSaveFiletypes`.
