### ISSUE TITLE
Deno linting applied to Node.js projects

### ISSUE THREAD

**Issue by brillout** [fannheyward/coc-deno#82]
I removed `coc-deno` and, still, the Deno linting applies to my Node.js projects.

**Comment by fannheyward** [comment]
Can't reproduce, if you removed coc-deno, there should not be any Deno extensions. Checkout `:CocList services`, `:CocList sources` and your `coc-settings.json`.

**Comment by brillout** [comment]
Thanks for the reply. I ended up using

```
command! -nargs=0 Prettier :CocCommand prettier.formatFile
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.json,*.vue,*.yaml,*.html Prettier
```

Not sure what happened.
